        # ll = LinkedList()
        # second_node = LinkedList(fake_value())
        # third_node = LinkedList(fake_value())
        # ll.append(second_node)
        # ll.append(third_node)
        # self.assertEqual(second_node, ll.next)